language: node_js
node_js:
  - "lts/*"
notifications:
  email: false
cache: false
sudo: required
script:
  - npm run test
branches:
  only:
    - master
jobs:
  include:
    - stage: build
      name: "Build"
      script: npm run build
    - name: "Build:dist"
      script: npm run build:dist
    - stage: deploy
      name: "Deploy - Site to gh-pages"
      script: skip
      before_deploy:
        - npm run build:site
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
        local_dir: .site
        on:
          branch: master
stages:
  - name: "Build"
  - name: "Build:dist"
  - name: "Deploy - Site to gh-pages"
    if: type != pull_request
